// Package tmux runs treeline's embedded terminal sessions on a tmux server
// of its own, so quitting treeline detaches from them instead of killing the
// work inside. The server has a dedicated socket and its own configuration,
// so these sessions never show up in the user's `tmux ls` and never inherit
// their prefix or keybindings.
package tmux

import (
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"sync"
	"time"
)

// Socket names the dedicated server: tmux -L treeline. It is a variable only
// so tests can work on a server of their own.
var Socket = "treeline"

// binary is the tmux executable, empty when tmux isn't installed.
var binary = sync.OnceValue(func() string {
	p, _ := exec.LookPath("tmux")
	return p
})

// Available reports whether sessions can be persisted at all.
func Available() bool { return binary() != "" }

// conf is the server's entire configuration: no status bar to eat a row of
// the pane, and no prefix key — treeline forwards every keystroke to the
// program, so tmux must not claim one. escape-time is dropped from the
// 500ms default so ESC reaches the program promptly. screen-256color rather
// than tmux-256color because that terminfo entry exists everywhere.
const conf = `# generated by treeline — rewritten on launch, edits are lost
set -g status off
set -g prefix None
set -g prefix2 None
set -s escape-time 10
set -g history-limit 10000
set -g default-terminal "screen-256color"
# mouse on makes the client ask the pane's terminal for wheel events, which
# is the only way scrolling can reach the history-limit lines above: the
# client is full-screen, so the pane itself never builds any scrollback.
set -g mouse on
`

// confFile writes conf under the cache directory once per process and
// returns its path. On failure it returns "": tmux then starts with the
// user's own config, which still works, just less tidily.
var confFile = sync.OnceValue(func() string {
	base, err := os.UserCacheDir()
	if err != nil {
		return ""
	}
	dir := filepath.Join(base, "treeline")
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return ""
	}
	p := filepath.Join(dir, "tmux.conf")
	if err := os.WriteFile(p, []byte(conf), 0o600); err != nil {
		return ""
	}
	return p
})

// Name is the session name for a kind of session ("claude", "shell") in a
// directory: readable enough to recognise in `treeline sessions`, with a
// digest of the path appended so same-named worktrees in different repos
// never collide.
func Name(kind, dir string) string {
	sum := sha256.Sum256([]byte(dir))
	return fmt.Sprintf("%s-%s-%s", kind, sanitize(filepath.Base(dir)), hex.EncodeToString(sum[:4]))
}

// sanitize keeps a name to characters tmux is happy with — "." and ":" are
// reserved for addressing windows and panes.
func sanitize(s string) string {
	var b strings.Builder
	for _, r := range s {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9', r == '-', r == '_':
			b.WriteRune(r)
		default:
			b.WriteRune('-')
		}
	}
	out := b.String() // ASCII only by now, so byte slicing is safe
	if len(out) > 40 {
		out = out[:40]
	}
	if out = strings.Trim(out, "-"); out == "" {
		return "dir"
	}
	return out
}

// Command attaches to the named session, creating it — running prog in dir —
// when it isn't there yet. The result is a tmux *client*: when it dies the
// session carries on running on the server.
func Command(name, dir, prog string, args ...string) *exec.Cmd {
	argv := []string{"-L", Socket}
	if c := confFile(); c != "" {
		argv = append(argv, "-f", c)
	}
	argv = append(argv, "new-session", "-A", "-s", name, "-c", dir, shellCommand(prog, args))
	// a server that outlives treeline was configured at ITS launch: re-assert
	// the mouse option on every attach so servers started before it existed
	// (or by an older treeline) pick it up without being killed.
	argv = append(argv, ";", "set-option", "-g", "mouse", "on")
	cmd := exec.Command(binary(), argv...)
	cmd.Dir = dir
	return cmd
}

// shellCommand renders the program to run as the single string tmux's
// new-session takes.
func shellCommand(prog string, args []string) string {
	parts := make([]string, 0, len(args)+1)
	for _, a := range append([]string{prog}, args...) {
		parts = append(parts, quote(a))
	}
	return strings.Join(parts, " ")
}

func quote(s string) string {
	if s != "" && !strings.ContainsAny(s, " \t\n\"'\\$`*?~|&;<>()[]{}#!") {
		return s
	}
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// Env strips the outer tmux's variables from an environment, so attaching
// from a treeline that is itself running inside tmux isn't refused as
// nesting.
func Env(base []string) []string {
	out := make([]string, 0, len(base))
	for _, kv := range base {
		if strings.HasPrefix(kv, "TMUX=") || strings.HasPrefix(kv, "TMUX_PANE=") {
			continue
		}
		out = append(out, kv)
	}
	return out
}

// ErrNoServer means treeline's tmux server isn't up: nothing has been started
// yet, or everything has been stopped. A normal state, not a fault.
var ErrNoServer = errors.New("no sessions running")

// Session is one live session on treeline's server.
type Session struct {
	Name     string
	Dir      string
	Attached bool
	Created  time.Time
}

// List returns the live sessions, empty when the server isn't running.
func List() ([]Session, error) {
	out, err := run("list-sessions", "-F",
		"#{session_name}\t#{session_path}\t#{session_attached}\t#{session_created}")
	if errors.Is(err, ErrNoServer) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	var sessions []Session
	for _, line := range strings.Split(strings.TrimSpace(out), "\n") {
		f := strings.Split(line, "\t")
		if len(f) < 4 {
			continue
		}
		s := Session{Name: f[0], Dir: f[1], Attached: f[2] != "0"}
		if secs, err := strconv.ParseInt(f[3], 10, 64); err == nil {
			s.Created = time.Unix(secs, 0)
		}
		sessions = append(sessions, s)
	}
	return sessions, nil
}

// Kill ends a session and the program inside it.
func Kill(name string) error {
	_, err := run("kill-session", "-t", name)
	return err
}

// KillDir ends the sessions belonging to a directory, for when the worktree
// itself is being removed. Best-effort: a session that was never started is
// not an error.
func KillDir(dir string) {
	if !Available() {
		return
	}
	for _, kind := range []string{"claude", "shell"} {
		_ = Kill(Name(kind, dir))
	}
}

// KillAll shuts the whole server down, ending every persisted session.
func KillAll() error {
	if _, err := run("kill-server"); err != nil && !errors.Is(err, ErrNoServer) {
		return err
	}
	return nil
}

// run invokes tmux against treeline's socket. A missing server comes back as
// ErrNoServer — tmux words that differently depending on version ("no server
// running" when it has just exited, "error connecting" when the socket was
// never there), so both are folded into the one sentinel.
func run(args ...string) (string, error) {
	if !Available() {
		return "", errors.New("tmux is not installed")
	}
	cmd := exec.Command(binary(), append([]string{"-L", Socket}, args...)...)
	cmd.Env = Env(os.Environ())
	out, err := cmd.CombinedOutput()
	if err != nil {
		msg := strings.TrimSpace(string(out))
		if strings.Contains(msg, "no server running") || strings.Contains(msg, "error connecting") {
			return msg, ErrNoServer
		}
		return msg, fmt.Errorf("tmux %s: %s", strings.Join(args, " "), msg)
	}
	return string(out), nil
}
