package ui

import "github.com/charmbracelet/bubbles/key"

// Key bindings, grouped for the bubbles/help bar. Movement keys inside the
// table and viewports are the components' own defaults.
var (
	keyOpen      = key.NewBinding(key.WithKeys("enter"), key.WithHelp("enter", "open/create"))
	keyJump      = key.NewBinding(key.WithKeys("o"), key.WithHelp("o", "cd into worktree"))
	keyCreate    = key.NewBinding(key.WithKeys("enter"), key.WithHelp("enter", "create worktree"))
	keyView      = key.NewBinding(key.WithKeys("v"), key.WithHelp("v", "details"))
	keyNew       = key.NewBinding(key.WithKeys("n"), key.WithHelp("n", "new"))
	keyDelete    = key.NewBinding(key.WithKeys("d"), key.WithHelp("d", "delete"))
	keyRefresh   = key.NewBinding(key.WithKeys("r"), key.WithHelp("r", "refresh"))
	keyFilter    = key.NewBinding(key.WithKeys("/"), key.WithHelp("/", "filter"))
	keySearchL   = key.NewBinding(key.WithKeys("s"), key.WithHelp("s", "search linear"))
	keyAuth      = key.NewBinding(key.WithKeys("a"), key.WithHelp("a", "linear"))
	keyGitHub    = key.NewBinding(key.WithKeys("g"), key.WithHelp("g", "github ci"))
	keyQuit      = key.NewBinding(key.WithKeys("q"), key.WithHelp("q", "quit"))
	keyBack      = key.NewBinding(key.WithKeys("esc"), key.WithHelp("esc", "back"))
	keyCancel    = key.NewBinding(key.WithKeys("esc"), key.WithHelp("esc", "cancel"))
	keyChoose    = key.NewBinding(key.WithKeys("up", "down"), key.WithHelp("↑/↓", "choose"))
	keyConfirm   = key.NewBinding(key.WithKeys("enter"), key.WithHelp("enter", "continue"))
	keyDoIt      = key.NewBinding(key.WithKeys("enter"), key.WithHelp("enter", "create"))
	keyChoose2   = key.NewBinding(key.WithKeys("left", "right"), key.WithHelp("←/→", "choose"))
	keyConfirm2  = key.NewBinding(key.WithKeys("enter"), key.WithHelp("enter", "confirm"))
	keyRemove    = key.NewBinding(key.WithKeys("y"), key.WithHelp("y", "remove"))
	keyRemoveB   = key.NewBinding(key.WithKeys("b"), key.WithHelp("b", "remove + delete branch"))
	keyForce     = key.NewBinding(key.WithKeys("y"), key.WithHelp("y", "force remove"))
	keyForceB    = key.NewBinding(key.WithKeys("b"), key.WithHelp("b", "force remove + delete branch"))
	keyField     = key.NewBinding(key.WithKeys("tab"), key.WithHelp("tab", "switch field"))
	keyApply     = key.NewBinding(key.WithKeys("enter"), key.WithHelp("enter", "apply"))
	keyClear     = key.NewBinding(key.WithKeys("esc"), key.WithHelp("esc", "clear filter"))
	keyOpenURL   = key.NewBinding(key.WithKeys("o"), key.WithHelp("o", "open browser"))
	keyPane      = key.NewBinding(key.WithKeys("tab"), key.WithHelp("tab", "switch pane"))
	keyStage     = key.NewBinding(key.WithKeys(" "), key.WithHelp("space", "stage/unstage"))
	keyHunks     = key.NewBinding(key.WithKeys("enter"), key.WithHelp("enter", "hunks"))
	keyLog       = key.NewBinding(key.WithKeys("l"), key.WithHelp("l", "log"))
	keyBranchD   = key.NewBinding(key.WithKeys("b"), key.WithHelp("b", "branch diff"))
	keyCommitC   = key.NewBinding(key.WithKeys("c"), key.WithHelp("c", "commit"))
	keyCommitGo  = key.NewBinding(key.WithKeys("ctrl+s"), key.WithHelp("ctrl+s", "commit"))
	keyGenMsg    = key.NewBinding(key.WithKeys("ctrl+g"), key.WithHelp("ctrl+g", "generate message"))
	keyTermEsc   = key.NewBinding(key.WithKeys("ctrl+q"), key.WithHelp("ctrl+q", "next pane"))
	keyTermTabs  = key.NewBinding(key.WithKeys("ctrl+t"), key.WithHelp("ctrl+t/ctrl+→", "shell tabs"))
	keySettingsK = key.NewBinding(key.WithKeys(","), key.WithHelp(",", "settings"))
	keyIDEOpen   = key.NewBinding(key.WithKeys("enter"), key.WithHelp("enter", "open/fold"))
	keyIDEEdit   = key.NewBinding(key.WithKeys("e"), key.WithHelp("e", "edit"))
	keyIDESave   = key.NewBinding(key.WithKeys("ctrl+s"), key.WithHelp("ctrl+s", "save"))
	keyIDESelect = key.NewBinding(key.WithKeys("shift+up", "shift+down"), key.WithHelp("shift+↑/↓", "select lines"))
	keyIDEIndent = key.NewBinding(key.WithKeys("tab", "shift+tab"), key.WithHelp("tab/shift+tab", "indent"))
	keyIDEMulti  = key.NewBinding(key.WithKeys("ctrl+e"), key.WithHelp("ctrl+e", "cursors on line ends"))
	keyIDEView   = key.NewBinding(key.WithKeys("esc"), key.WithHelp("esc", "stop editing"))
	keyIDETree   = key.NewBinding(key.WithKeys("esc"), key.WithHelp("esc", "file tree"))
	keyIDEFind   = key.NewBinding(key.WithKeys("/"), key.WithHelp("/", "find · n/N next"))
	keyIDEFilter = key.NewBinding(key.WithKeys("/"), key.WithHelp("/", "filter"))
	keyIDETabs   = key.NewBinding(key.WithKeys("[", "]"), key.WithHelp("[/]", "tabs"))
	keyIDEClose  = key.NewBinding(key.WithKeys("x"), key.WithHelp("x", "close"))
	keyIDENew    = key.NewBinding(key.WithKeys("a"), key.WithHelp("a", "new"))
	keyIDERename = key.NewBinding(key.WithKeys("R"), key.WithHelp("R", "rename"))
	keyIDEDel    = key.NewBinding(key.WithKeys("d"), key.WithHelp("d", "delete"))
	keyEditRepo  = key.NewBinding(key.WithKeys("enter"), key.WithHelp("enter", "edit"))
	keyAddRepo   = key.NewBinding(key.WithKeys("a"), key.WithHelp("a", "add repo"))
	keyDelRepo   = key.NewBinding(key.WithKeys("x"), key.WithHelp("x", "remove"))
)
